name: 03 - workflow runners
on: workflow_dispatch
jobs:
    show-OS:
        runs-on: ubuntu-latest
        steps:
            - name: show OS
              run: |
                echo " runs on: $RUNNER_OS"
    show-other-OS:
        runs-on: windows-latest
        steps:
            - name: show other OS
              shell: bash
              run: |
                echo " runs on: $RUNNER_OS"


