name: context-file
on: workflow_dispatch

env:
    MY_ENV_VARIABLE: 'step'
jobs:
    echo-context:
        env:
            MY_ENV_VARIABLE: 'job'
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "event: ${{github.event}}"
                echo "Ref: ${{github.ref}}"
                echo "sha: ${{github.sha}}"
                echo "actor: ${{github.actor}}"
                echo "workflow: ${{github.workflow}}"
                echo "run-id: ${{github.run_id}}"
            - env:
                MY_ENV_VARIABLE: 'context'
              run: |
                echo "variable: ${{vars.MY_VAR}}"
                echo "env: ${{env.MY_ENV_VARIABLE}}"


