name: 07-expressions
on:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print start up data'
              if: ${{inputs.debug}} && 'OFF'
              run: |
                echo "Triggered by: ${{github.event}}"
                echo "Branch: ${{github.ref}}"
                echo "OS: ${{runner.os}}"
            - name: Greetings
              run: echo "hello world"
