name: 07-expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print start up data'
              if: ${{inputs.debug}}
              run: |
                echo "Triggered by: ${{github.event}}"
                echo "Branch: ${{github.ref}}"
                echo "OS: ${{runner.os}}"
