name: 08-variables
on:
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: 'I am a workflow env var'
    OVERWRITTEN: 'I will be overwritten'
jobs:
    echo:
        env:
            JOB_VAR: 'I am a job env var'
            OVERWRITTEN: 'I have been overwritten at the job level'
        runs-on: ubuntu-latest
        steps:
            - env:
                STEP_VAR: 'I am a step env var'
                step_var2: 'I am another step var'
              run: |
                echo "step env var: ${{env.STEP_VAR}}"
                echo "step env var2: ${{env.step_var2}}"
                echo "job env var: ${{env.JOB_VAR}}"
                echo "workflow env var: ${{env.WORKFLOW_VAR}}"
                echo "overwritten var: ${{env.OVERWRITTEN}}"
            - env:
                OVERWRITTEN: 'I have been overwritten at the step level'
              run: |
                echo "overwritten var: ${{env.OVERWRITTEN}}"

