name: 09-controlling-expressions
on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: true

jobs:
    test-expression:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test"
            - if: ${{ inputs.debug == false }}
              run: exit 1
            - if: ${{cancelled()}}
              run: echo "cancelled"
