name: test_docker_access
on: push
jobs:
    display:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}